### ISSUE TITLE
Why not use package manager for installing node?

### ISSUE THREAD

**Issue by spk83** [andrewrothstein/ansible-node#1]
This way role could support Alpine as well. Happy to raise PR

**Comment by spk83** [comment]
Would translate this to the role - https://nodejs.org/en/download/package-manager/

**Comment by andrewrothstein** [comment]
I want to fix/declare the version which is doable but substantially more effort when considering the varied package naming conventions across the platforms. if you want a light and tight node container image then use those provided on the hub. They're alpine based, small, and awesome.
